
setup;

expDir = 'data';

get_imdb('modelnet40', ...
  'func', @(s) setup_imdb_modelnet_notest(s), ...
  'rebuild', true);

cnn_shape('modelnet40', ...
'expDir', fullfile(expDir,'deploynet'), ...
'numFetchThreads', 12, ...
'pad', 32, ...
'border', 32, ...
'multiview', true, ...
'batchSize', 5, ...
'gpus', [], ...
'maxIterPerEpoch', Inf, ...
'numEpochs', [0 30], ...
'learningRate', [0.0005*ones(1,10) 0.0001*ones(1,10) 0.00001*ones(1,10)] ...
);
